apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxysql
  template:
    metadata:
      labels:
        app: proxysql
    spec:
      containers:
      - name: proxysql
        image: proxysql/proxysql
        ports:
        - containerPort: 6033
        - containerPort: 6032
        resources:
          limits:
            cpu: 500m  
            memory: 512Mi
          requests:
            cpu: 200m  
            memory: 256Mi
