apiVersion: v1
kind: Service
metadata:
  name: proxysql
spec:
  ports:
  - name: proxysql-db1
    port: 6033
    targetPort: 6033
  - name: proxysql-db2
    port: 6032
    targetPort: 6032
  selector:
    app: proxysql
